project_id = "jjsmiryavfgkvgdshzeq"

[functions.analyze-image]
verify_jwt = false

[functions.analyze-image-public]
verify_jwt = false

[functions.generate-after-image]
verify_jwt = false

[functions.generate-after-image-public]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.get-paddle-price]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.redeem-promo]
verify_jwt = false
